export const SIGNUP_ACTION = "[action] signup user";
export const LOGIN_ACTION = "[action] login user";
export const LOGOUT_ACTION = "[action] logout user";
export const AUTH_ACTION = "[action] auth";
export const AUTO_LOGIN_ACTION = "[action] auto login";
export const GET_USER_TOKEN_GETTER = "[getter] get user token";
export const IS_USER_AUTHENTICATED_GETTER = "[getter] is user authenticated";
export const SET_USER_TOKEN_DATA_MUTATION = "[mutations] set user token data";
export const LOADING_BAR_SHOW_MUTATION = "[mutations] show loading bar";
